add_newline = false

format = "$directory$git_branch$git_status$python$character"

[character]
success_symbol = "[>](white)"
error_symbol = "[>](red)"

[git_branch]
symbol = " "
style = "red"
format = "[$symbol]($style)"

[python]
style = "yellow"
format = "[$virtualenv]($style)"