add_newline = false

format = "$os $directory$git_branch$git_status$python$character"

[os]
disabled = false
style = "blue"

[os.symbols]
Fedora = ""
Arch = "󰣇"
Debian = "󰣚"

[python]
symbol = "  "
style = "yellow"
format = "[$symbol($version)]($style)"

[git_branch]
symbol = " "
style = "red"
format = "[$symbol$branch]($style)"

[character]
success_symbol = "[>](white)"
error_symbol = "[>](red)"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Videos" = ""